CREATE DATABASE BANKING;
CREATE SCHEMA RAW;

CREATE TABLE CUSTOMERS (V VARIANT);
CREATE TABLE accounts (V VARIANT);
create TABLE Transactions (V VARIANT);

SELECT * FROM ACCOUNTS;

GRANT ALL ON DATABASE BANKING TO ROLE NETFLIX_JADEN_DATA;
GRANT ALL ON ALL SCHEMAS IN DATABASE BANKING TO ROLE NETFLIX_JADEN_DATA;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE BANKING TO ROLE NETFLIX_JADEN_DATA;
GRANT ALL ON ALL TABLES IN SCHEMA BANKING.RAW TO ROLE NETFLIX_JADEN_DATA;
GRANT ALL ON FUTURE TABLES IN SCHEMA BANKING.RAW TO ROLE NETFLIX_JADEN_DATA;

SELECT * FROM STG_ACCOUNTS;
SELECT * FROM STG_CUSTOMERS;
SELECT * FROM STG_TRANSACTIONS;

DROP VIEW IF EXISTS STG_ACCOUNTS;
DROP VIEW IF EXISTS STG_CUSTOMERS;
DROP VIEW IF EXISTS STG_TRANSACTIONS;

SELECT * FROM BANKING.ANALYTICS.ACCOUNTS_SNAPSHOT;
SELECT * FROM BANKING.ANALYTICS.CUSTOMERS_SNAPSHOT;

SELECT * FROM BANKING.MARTS.DIM_ACCOUNTS;
SELECT * FROM BANKING.MARTS.DIM_CUSTOMERS;
SELECT * FROM BANKING.MARTS.FACT_TRANSACTIONS;